name: rt-detr-poles
cv_name: null

epochs: 30
optimized_metric: "metrics/val/ccq/masked/quality/0.004"  # set by the HPO script
verbose: false

checkpoint:
  resume: false
  run_id: null
  epoch: null

data:
  augmentations:
    cj_magnitude: 0.2
    multi_scale_prob: 0.5

  downsampling_factor: 32
  patch_size: 1024
  perturbation: 384
  negative_sample_prob: 0.12
  non_sky_bias: 0.5
  batch_size: 16
  cv:
    num_folds: 5
    fold: null
    folds_select: null
    parallel: []
  size:
    train: null
    val: null
  num_workers:
    train: 8
    val: 2

optimizer:
  lr: 0.0001
  lr_backbone: 0.00001
  betas: [0.9, 0.999]
  wd: 0.0001
  params:
    - params: '^(?=.*backbone)(?=.*norm).*$'
      lr: ${optimizer.lr_backbone}
      weight_decay: 0.
    - params: '^(?=.*backbone)(?!.*norm).*$'
      lr: ${optimizer.lr_backbone}
    - params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bias)).*$'
      weight_decay: 0.

lr_scheduler:
  enabled: false
  type: MultiStepLR
  milestones: [1000]
  gamma: 0.1

paths:
  complete_frames: /scratch/cvlab/home/gwizdala/dataset/processed/daedalean/complete_frames
  annotations: /scratch/cvlab/home/gwizdala/dataset/daedalean/cable-annotations

sahi:
  step_size_fraction: 0.8
  patch_sizes:
    - 256
    - 512
    - 1024
  predict_on_full_image: true
  batch_size: 8
  min_score: 0.5

validation:
  every: true
  last: false

visualization:
  n_images_per_epoch: 5
  every: 1
